---
- name: join-win-ad | install packages
  yum:
    name:
      - sssd
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - adcli
      - samba-common
      - samba-common-tools
      - krb5-workstation
      - openldap-clients
      - policycoreutils-python
    state: present

- name: join-win-ad | install epel repo
  yum: name=epel-release state=present

- name: join-win-ad | install pip
  yum: name=python-pip state=present


- name: join-win-ad | verify DNS1 setup
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DNS1='
    line: "DNS1={{ active_directory.ip | default('1.1.1.1') }}"
    state: present
  register: tasks_result


- name: join-win-ad | verify DNS domain search
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DOMAIN='
    line: "DOMAIN={{ active_directory.domain | default('domain.com') }}"
    state: present
  register: tasks_result


- name: Reboot system
  reboot:
    reboot_timeout: 120
  when: tasks_result.changed
